### ISSUE TITLE
Trying to clone an uncloneable object of class PDO

### ISSUE THREAD

**Issue by sinstudioph** [paragonie/easydb#134]
<h1>Slim Application Error</h1>
	<p>The application could not run because of the following error:</p>
	<h2>Details</h2>
	<div><strong>Type:</strong> Error</div>
	<div><strong>Message:</strong> Trying to clone an uncloneable object of class PDO</div>
	<div><strong>File:</strong> D:\xampp\htdocs\sin-studio-api\vendor\paragonie\easydb\src\EasyDB.php</div>
	<div><strong>Line:</strong> 37</div>
	<h2>Trace</h2>
	<pre>#0 D:\xampp\htdocs\sin-studio-api\vendor\paragonie\easydb\src\Factory.php(68): ParagonIE\EasyDB\EasyDB-&gt;__construct(Object(PDO), 'mysql')
#1 D:\xampp\htdocs\sin-studio-api\index.php(34): ParagonIE\EasyDB\Factory::create('mysql:host=loca...', 'root', '')
#2 D:\xampp\htdocs\sin-studio-api\vendor\pimple\pimple\src\Pimple\Container.php(122): {closure}(Object(Slim\Container))
#3 D:\xampp\htdocs\sin-studio-api\vendor\slim\slim\Slim\Container.php(109): Pimple\Container-&gt;offsetGet('db')
#4 D:\xampp\htdocs\sin-studio-api\routes\event.php(8): Slim\Container-&gt;get('db')
#5 [internal function]: Closure-&gt;{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 D:\xampp\htdocs\sin-studio-api\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(40): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#7 D:\xampp\htdocs\sin-studio-api\vendor\slim\slim\Slim\Route.php(281): Slim\Handlers\Strategies\RequestResponse-&gt;__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#8 D:\xampp\htdocs\sin-studio-api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\Route-&gt;__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 D:\xampp\htdocs\sin-studio-api\vendor\slim\slim\Slim\Route.php(268): Slim\Route-&gt;callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 D:\xampp\htdocs\sin-studio-api\vendor\slim\slim\Slim\App.php(503): Slim\Route-&gt;run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 D:\xampp\htdocs\sin-studio-api\index.php(50): Slim\App-&gt;__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 [internal function]: Closure-&gt;{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#13 D:\xampp\htdocs\sin-studio-api\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)
#14 [internal function]: Slim\DeferredCallable-&gt;__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#15 D:\xampp\htdocs\sin-studio-api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#16 D:\xampp\htdocs\sin-studio-api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App-&gt;Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 D:\xampp\htdocs\sin-studio-api\vendor\slim\slim\Slim\App.php(392): Slim\App-&gt;callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 D:\xampp\htdocs\sin-studio-api\vendor\slim\slim\Slim\App.php(297): Slim\App-&gt;process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 D:\xampp\htdocs\sin-studio-api\index.php(77): Slim\App-&gt;run()
#20 {main}

**Comment by sinstudioph** [comment]
Just found similar issue and updating the package fixes it,  closing this  one. 
PRETTY Please update your .README file to use version 2.0.1.
